# Generated by Django 4.2.1 on 2023-05-23 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phonenumber', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('lvl', models.CharField(max_length=30)),
                ('GPA', models.CharField(max_length=30)),
                ('s_type', models.CharField(max_length=30)),
                ('depart', models.CharField(max_length=30)),
            ],
        ),
    ]
