# Generated by Django 4.2.1 on 2023-05-24 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentAffairs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='students',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('phonenumber', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('lvl', models.IntegerField()),
                ('GPA', models.IntegerField()),
                ('s_type', models.CharField(max_length=30)),
                ('depart', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='student',
        ),
    ]
