# Generated by Django 4.2.1 on 2023-05-24 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentAffairs', '0003_students_dob_alter_students_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('NationalId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('FullName', models.CharField(max_length=20)),
                ('UserName', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
                ('ConfirmPassword', models.CharField(max_length=20)),
                ('PhoneNumber', models.CharField(max_length=11)),
                ('Date', models.DateField(default='2000-01-01')),
            ],
        ),
    ]
