# Generated by Django 4.2.1 on 2023-05-25 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentAffairs', '0004_admin'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='logedIN',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
