# Generated by Django 4.2.1 on 2023-05-25 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentAffairs', '0005_admin_logedin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='GPA',
            field=models.FloatField(),
        ),
    ]
