# Generated by Django 4.2.1 on 2023-05-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentAffairs', '0006_alter_students_gpa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='UserName',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
