# Generated by Django 4.2.1 on 2023-05-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentAffairs', '0007_alter_admin_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='dfdf',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
