# Generated by Django 4.2.1 on 2023-05-25 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('StudentAffairs', '0008_admin_dfdf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admin',
            name='dfdf',
        ),
    ]
