# Generated by Django 4.2.1 on 2023-05-25 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentAffairs', '0009_remove_admin_dfdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='NationalId',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='admin',
            name='UserName',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
