# Generated by Django 4.2.1 on 2023-05-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentAffairs', '0010_alter_admin_nationalid_alter_admin_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='student_id',
            field=models.IntegerField(null=True),
        ),
    ]
