# Generated by Django 4.2.1 on 2023-06-01 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StudentAffairs', '0013_admin_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
